// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// x  O  x  x  O   x   x  O    x   x
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

const f = [1,2];

const fibGenerator = ( inputArray ) => {
    let len = inputArray.length;
    if ( inputArray[len-1] + inputArray[len-2] < 4000001 ){
        inputArray.push( inputArray[len - 1] + inputArray[len - 2] );
        return fibGenerator( inputArray );
    } else {
        return inputArray;
    }
}
// const populatedF = fibGenerator(f);
// const evenF = populatedF.filter( e => e%2 === 0 );
// console.log(evenF.reduce( (a,b) =>  a+b  ));